import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Navbar
    'nav.title': "FINORA'NIN",
    'nav.title_accent': 'SIRT ÇANTASI',
    'nav.home': 'Ana Sayfa',
    'nav.tools': 'Araçlar',
    'nav.image_analysis': 'Görsel Analiz & Format',
    'nav.binary_converter': 'Binary Dönüştürücü',
    'nav.password_generator': 'Şifre Oluşturucu',
    'nav.morse_converter': 'Mors Dönüştürücü',
    'nav.color_explorer': 'Renk Gezgini',
    'nav.favicon_generator': 'Favicon Oluşturucu',
    'nav.json_converter': 'JSON Model Dönüştürücü',
    'nav.ascii_art': 'ASCII Sanatı Oluşturucu',
    'nav.qr_code': 'QR Kod Oluşturucu',
    'nav.pomodoro': 'Pomodoro Zamanlayıcı',
    'nav.word_counter': 'Kelime Sayacı',
    
    // Home
    'home.badge': 'DİJİTAL ARAÇ KİTİ V1.0',
    'home.title': "FINORA'NIN",
    'home.title_accent': 'SIRT ÇANTASI',
    'home.description': "Finora'nın sırt çantası, geliştiriciler ve tasarımcılar için tasarlanmış modern, hızlı ve güvenli araçlar sunar. Tüm işlemler tarayıcınızda gerçekleşir.",
    'home.cta_start': 'Hemen Başla',
    'home.cta_github': 'GitHub\'da İncele',
    'home.features_title': 'Neden Finora?',
    'home.feature_secure': 'Güvenli',
    'home.feature_secure_desc': 'Verileriniz asla sunucularımıza gönderilmez.',
    'home.feature_fast': 'Hızlı',
    'home.feature_fast_desc': 'Anlık dönüşüm ve analiz sonuçları.',
    'home.feature_modern': 'Modern',
    'home.feature_modern_desc': 'Kullanıcı dostu ve şık arayüz.',

    // Common
    'common.copy': 'KOPYALA',
    'common.copied': 'KOPYALANDI',
    'common.clear': 'Temizle',
    'common.input': 'Giriş',
    'common.output': 'Çıkış',
    'common.result_placeholder': 'Sonuç burada görünecek...',
    'common.random': 'Rastgele',
    'common.info': 'BİLGİ',
    'common.pro_tip': 'İPUCU',

    // Binary Tool
    'binary.title': 'BINARY',
    'binary.title_accent': 'DÖNÜŞTÜRÜCÜ',
    'binary.desc': 'Metin ve Binary (ikilik sistem) arasında anında dönüşüm yapın.',
    'binary.mode_text': 'METİN',
    'binary.mode_binary': 'BINARY',
    'binary.placeholder_text': 'Dönüştürülecek metni buraya yazın...',
    'binary.placeholder_binary': '01001000 01100101 01101100 01101100 01101111',

    // Password Tool
    'password.title': 'ŞİFRE',
    'password.title_accent': 'OLUŞTURUCU',
    'password.desc': 'Güvenli ve kırılması zor şifreler oluşturun.',
    'password.length': 'ŞİFRE UZUNLUĞU',
    'password.settings': 'KARAKTER AYARLARI',
    'password.uppercase': 'Büyük Harf (ABC)',
    'password.lowercase': 'Küçük Harf (abc)',
    'password.numbers': 'Rakamlar (123)',
    'password.symbols': 'Semboller (#$&)',
    'password.strength': 'GÜVENLİK SEVİYESİ',
    'password.strength_very_weak': 'ÇOK ZAYIF',
    'password.strength_weak': 'ZAYIF',
    'password.strength_medium': 'ORTA',
    'password.strength_strong': 'GÜÇLÜ',
    'password.strength_very_strong': 'ÇOK GÜÇLÜ',
    'password.generate': 'YENİ ŞİFRE ÜRET',

    // Morse Tool
    'morse.title': 'MORS',
    'morse.title_accent': 'DÖNÜŞTÜRÜCÜ',
    'morse.desc': 'Metin ve Mors alfabesi arasında anında dönüşüm yapın.',
    'morse.listen': 'DİNLE',
    'morse.info_text': 'Kelimeler arası ayrım için \'/\' karakteri kullanılır. Her harf arasında bir boşluk bırakılır.',

    // Color Tool
    'color.title': 'RENK',
    'color.title_accent': 'GEZGİNİ',
    'color.desc': 'Gelişmiş renk seçici ile mükemmel armonileri yakalayın.',
    'color.hue': 'Ton (Hue)',
    'color.selected': 'Seçili Renk',
    'color.rgb_values': 'RGB Değerleri',
    'color.palette_title': 'Akıllı Renk Paleti',
    'color.pro_tip_text': 'Renk seçici HSV modelini kullanır. Bu model, insan gözünün renkleri algılama biçimine daha yakındır.',

    // Image Tool
    'image.title': 'GÖRSEL',
    'image.title_accent': 'ANALİZ',
    'image.desc': 'Görsellerinizi analiz edin, formatlarını değiştirin ve detayları görün.',
    'image.drop': 'Görseli buraya sürükleyin veya seçmek için tıklayın',
    'image.analyzing': 'Analiz ediliyor...',
    'image.details': 'Görsel Detayları',
    'image.format': 'Format',
    'image.dimensions': 'Boyutlar',
    'image.size': 'Dosya Boyutu',
    'image.actions': 'İşlemler',
    'image.convert_to': 'Formatına Dönüştür',

    // Favicon Tool
    'favicon.title': 'FAVICON',
    'favicon.title_accent': 'OLUŞTURUCU',
    'favicon.desc': 'Logonuzu tüm tarayıcı ve cihazlar için profesyonel bir favicon paketine dönüştürün.',
    'favicon.download_pack': 'PAKETİ İNDİR (.ZIP)',
    'favicon.html_code': 'HTML KODU',
    'favicon.preview_all': 'Tüm Boyutları Önizle',
    'favicon.info_text': 'Oluşturulan paket; 16x16, 32x32, 180x180 (Apple Touch) ve 192x192, 512x512 (Android) boyutlarını içerir.',

    // JSON Converter Tool
    'json.title': 'JSON',
    'json.title_accent': 'MODEL DÖNÜŞTÜRÜCÜ',
    'json.desc': 'JSON verilerinizi anında TypeScript, Go veya Java modellerine dönüştürün.',
    'json.placeholder': 'JSON verisini buraya yapıştırın...',
    'json.select_lang': 'HEDEF DİL SEÇİN',
    'json.root_name': 'KÖK SINIF ADI',
    'json.error_invalid': 'Geçersiz JSON formatı. Lütfen kontrol edin.',
    'json.empty_warning': 'Dönüştürülecek JSON verisi bulunamadı.',

    // ASCII Tool
    'ascii.title': 'ASCII',
    'ascii.title_accent': 'SANATI OLUŞTURUCU',
    'ascii.desc': 'Metinlerinizi veya görsellerinizi havalı ASCII karakterlerine dönüştürün.',
    'ascii.mode_text': 'METİN',
    'ascii.mode_image': 'GÖRSEL',
    'ascii.placeholder': 'ASCII sanatına dönüştürülecek metni yazın...',
    'ascii.settings': 'AYARLAR',
    'ascii.font': 'YAZI TİPİ',
    'ascii.width': 'GENİŞLİK',
    'ascii.contrast': 'KONTRAST',
    'ascii.chars': 'KARAKTER SETİ',
    'tools.title': 'ARAÇ',
    'tools.title_accent': 'KATALOĞU',
    'tools.launch': 'ARACI BAŞLAT',

    // QR Code Tool
    'qr.title': 'QR KOD',
    'qr.title_accent': 'OLUŞTURUCU',
    'qr.desc': 'URL, metin, e-posta veya telefon numarası için anında QR kod oluşturun.',
    'qr.input_type': 'GİRDİ TÜRÜ',
    'qr.input_label': 'İÇERİK',
    'qr.type_url': 'URL',
    'qr.type_text': 'METİN',
    'qr.type_email': 'E-POSTA',
    'qr.type_phone': 'TELEFON',
    'qr.placeholder_text': 'QR koda dönüştürülecek metni yazın...',
    'qr.generate': 'QR KOD OLUŞTUR',
    'qr.generating': 'OLUŞTURULUYOR...',
    'qr.generated': 'QR KOD HAZIR',
    'qr.download': 'PNG İNDİR',
    'qr.preview_placeholder': 'QR kodunuz burada görünecek...',
    'qr.error_empty': 'Lütfen bir değer girin.',
    'qr.error_generate': 'QR kod oluşturulurken bir hata oluştu.',
    'qr.info_text': 'QR kodlar yüksek hata düzeltme seviyesi (H) ile oluşturulur. Tüm işlemler tarayıcınızda gerçekleşir, verileriniz hiçbir sunucuya gönderilmez.',

    // Pomodoro Tool
    'pomodoro.title': 'POMODORO',
    'pomodoro.title_accent': 'ZAMANLAYICI',
    'pomodoro.desc': 'Pomodoro tekniği ile odaklanın, üretkenliğinizi artırın.',
    'pomodoro.session_length': 'OTURUM SÜRESİ',
    'pomodoro.presets': 'HIZLI AYARLAR',
    'pomodoro.start': 'BAŞLAT',
    'pomodoro.pause': 'DURAKLAT',
    'pomodoro.resume': 'DEVAM ET',
    'pomodoro.reset': 'SIFIRLA',
    'pomodoro.times_up': 'SÜRE DOLDU!',
    'pomodoro.status_running': 'ODAKLANMA MODU',
    'pomodoro.status_paused': 'DURAKLATILDI',
    'pomodoro.status_ready': 'BAŞLAMAYI BEKLİYOR',
    'pomodoro.technique': 'POMODORO TEKNİĞİ',
    'pomodoro.tip_focus': '25 dk Odaklanın',
    'pomodoro.tip_focus_desc': 'Tek bir göreve kesintisiz odaklanın. Bildirimlerinizi kapatın.',
    'pomodoro.tip_break': '5 dk Mola Verin',
    'pomodoro.tip_break_desc': 'Her oturum sonunda kısa bir mola verin. Her 4 oturumda uzun mola.',
    'pomodoro.info_text': 'Pomodoro Tekniği, Francesco Cirillo tarafından geliştirilmiş bir zaman yönetimi yöntemidir. Tüm işlemler tarayıcınızda gerçekleşir.',

    // Word Counter Tool
    'wordcounter.title': 'KELİME',
    'wordcounter.title_accent': 'SAYACI',
    'wordcounter.desc': 'Metninizi yapıştırın ve kelime, karakter, cümle ve paragraf sayısını anında görün.',
    'wordcounter.input_label': 'METNİNİZ',
    'wordcounter.placeholder': 'Metninizi buraya yazın veya yapıştırın...',
    'wordcounter.paste': 'YAPIŞTIR',
    'wordcounter.words': 'KELİME',
    'wordcounter.characters': 'KARAKTER',
    'wordcounter.chars_no_space': 'BOŞLUKSUZ',
    'wordcounter.sentences': 'CÜMLE',
    'wordcounter.paragraphs': 'PARAGRAF',
    'wordcounter.read_time': 'okuma süresi',
    'wordcounter.info_text': 'İstatistikler siz yazarken anlık olarak güncellenir. Tüm işlemler tarayıcınızda gerçekleşir.',
    
    'nav.unix_timestamp': 'Unix Zaman Dönüştürücü',
    'nav.url_shortener': 'URL Kısaltıcı',
    
    // Unix Tool
    'unix.title': 'UNIX ZAMAN',
    'unix.title_accent': 'DÖNÜŞTÜRÜCÜ',
    'unix.desc': 'Zaman damgaları ve tarihler arasında anında ve kolayca çift yönlü dönüşüm yapın.',
    'unix.current_epoch': 'ANLIK UNIX ZAMAN DAMGASI',
    'unix.local_time': 'Yerel Tarih & Saat',
    'unix.utc_time': 'UTC Tarih & Saat',
    'unix.relative_time': 'Göreceli Zaman',
    'unix.convert_from_epoch': 'Unix Zaman Damgasını Çevir',
    'unix.convert_to_epoch': 'Tarihi Unix Zaman Damgasına Çevir',
    'unix.placeholder_epoch': 'Saniye veya milisaniye damgası girin...',
    'unix.btn_now': 'Şu Anı Getir',
    'unix.seconds': 'Saniye',
    'unix.milliseconds': 'Milisaniye',
    'unix.date_select': 'Bir Tarih Seçin',

    // URL Shortener
    'url.title': 'URL',
    'url.title_accent': 'KISALTICI',
    'url.desc': 'Uzun web bağlantılarınızı kısaltın, QR kodlarını oluşturun ve detaylarını analiz edin.',
    'url.placeholder': 'Kısaltılacak uzun URL\'i girin (https://... veya http://...)',
    'url.shorten': 'KISALT',
    'url.shortening': 'KISALTILIYOR...',
    'url.result_label': 'KISALTILMIŞ URL',
    'url.qr_title': 'BAĞLANTI QR KODU',
    'url.analysis_title': 'URL BİLEŞEN ANALİZİ',
    'url.param_name': 'PARAMETRE',
    'url.param_value': 'DEĞER',
    'url.error_invalid': 'Lütfen geçerli bir URL girin (http:// veya https:// ile başlamalıdır).',
    'url.error_failed': 'URL kısaltılırken bir hata oluştu. Lütfen tekrar deneyin.',

    'nav.linkbag': 'Finora LinkBag',
    
    // LinkBag Tool
    'linkbag.title': 'FINORA',
    'linkbag.title_accent': 'LINKBAG',
    'linkbag.desc': 'Bağlantılarınızı tek bir sayfada toplayan şık ve premium bir profil tasarlayın, paylaşın veya indirin.',
    'linkbag.editor': 'PROFİL DÜZENLEYİCİ',
    'linkbag.preview': 'CANLI ÖNİZLEME',
    'linkbag.profile_name': 'Adınız / Başlık',
    'linkbag.profile_bio': 'Kısa Biyografi',
    'linkbag.profile_avatar': 'Profil Resmi (URL)',
    'linkbag.profile_avatar_upload': 'Görsel Seç (Base64)',
    'linkbag.add_link': 'BAĞLANTI EKLE',
    'linkbag.link_title': 'Bağlantı Adı',
    'linkbag.link_url': 'URL Adresi',
    'linkbag.link_icon': 'İkon',
    'linkbag.select_theme': 'TEMA SEÇİMİ',
    'linkbag.theme_glass': 'Glassmorphism',
    'linkbag.theme_cyberpunk': 'Cyberpunk',
    'linkbag.theme_minimalist': 'Minimalist',
    'linkbag.theme_brutalism': 'Neo-Brutalism',
    'linkbag.theme_synthwave': 'Synthwave',
    'linkbag.theme_matrix': 'Matrix',
    'linkbag.theme_sakura': 'Cozy Sakura',
    'linkbag.theme_holographic': 'Aurora Hologram',
    'linkbag.theme_claymorphism': 'Claymorphism',
    'linkbag.share_profile': 'PAYLAŞIM LİNKİNİ KOPYALA',
    'linkbag.download_html': 'HTML DOSYASI İNDİR',

    'nav.cipher': 'Şifreleme & Deşifreleme',
    'nav.file_share': 'Dosya Paylaşımı',
    
    // File Share Tool
    'fileshare.title': 'DOSYA',
    'fileshare.title_accent': 'PAYLAŞIMI & DEPOLAMA',
    'fileshare.desc': 'Dosyalarınızı güvenle yükleyin, parolayla şifreleyin, süre sınırı koyun ve bağlantı veya QR kod ile anında paylaşın.',
    'fileshare.drop_title': 'Dosyanızı buraya sürükleyin veya seçmek için tıklayın',
    'fileshare.drop_sub': 'Tüm dosya formatları desteklenir (Görsel, Video, Doküman, ZIP vb.)',
    'fileshare.select_file': 'DOSYA SEÇ',
    'fileshare.file_details': 'DOSYA DETAYLARI',
    'fileshare.filename': 'Dosya Adı',
    'fileshare.filesize': 'Dosya Boyutu',
    'fileshare.filetype': 'Tür',
    'fileshare.uploaded_at': 'Yüklenme Tarihi',
    'fileshare.security_settings': 'GÜVENLİK VE SÜRE AYARLARI',
    'fileshare.enable_password': 'Parola Koruması Ekle (AES-256 Şifreleme)',
    'fileshare.password_placeholder': 'Dosya erişim parolası girin...',
    'fileshare.retention': 'Geçerlilik Süresi',
    'fileshare.retention_1h': '1 Saat',
    'fileshare.retention_24h': '24 Saat',
    'fileshare.retention_7d': '7 Gün',
    'fileshare.retention_30d': '30 Gün',
    'fileshare.retention_never': 'Süresiz (İstemci Depolama)',
    'fileshare.upload_btn': 'DOSYAYI YÜKLE VE BAĞLANTI OLUŞTUR',
    'fileshare.uploading': 'ŞİFRELENİYOR & YÜKLENİYOR...',
    'fileshare.share_link': 'PAYLAŞIM BAĞLANTISI',
    'fileshare.download_link': 'DOĞRUDAN İNDİRME LİNKİ',
    'fileshare.qr_title': 'MOBİL QR İNDİRME KODU',
    'fileshare.preview_title': 'DOSYA ÖNİZLEME',
    'fileshare.download_btn': 'DOSYAYI İNDİR',
    'fileshare.decrypt_title': 'KORUMALI DOSYA ERİŞİMİ',
    'fileshare.enter_password': 'Dosyayı indirmek / görüntülemek için parolayı girin:',
    'fileshare.decrypt_btn': 'ŞİFREYİ ÇÖZ VE AÇ',
    'fileshare.wrong_password': 'Hatalı parola! Lütfen tekrar deneyin.',
    'fileshare.history_title': 'YÜKLENEN DOSYALARIM / GEÇMİŞ',
    'fileshare.no_history': 'Henüz yüklenmiş dosya bulunmuyor.',
    'fileshare.downloads': 'İndirme',
    'fileshare.expires': 'Son Kullanma',
    'fileshare.delete': 'Sil',
    'fileshare.info_text': 'Bu dosya paylaşım aracı, dosyalarınızı Web Crypto API (AES-256) ile istemci tarafında şifreler ve güvenli paylaşım bağlantıları oluşturur.',
    
    // Cipher Tool
    'cipher.title': 'ŞİFRELEME &',
    'cipher.title_accent': 'DEŞİFRELEME',
    'cipher.desc': 'Sezar ve modern şifreleme yöntemleri ile metinlerinizi güvenle şifreleyin veya çözün.',
    'cipher.mode_encrypt': 'ŞİFRELE',
    'cipher.mode_decrypt': 'DEŞİFRELE',
    'cipher.settings': 'ŞİFRELEME AYARLARI',
    'cipher.algorithm': 'ŞİFRELEME ALGORİTMASI',
    'cipher.algo_caesar': 'Sezar Şifrelemesi (Caesar Cipher)',
    'cipher.algo_vigenere': 'Vigenère Şifrelemesi (Vigenère Cipher)',
    'cipher.algo_rot13': 'ROT13 Şifrelemesi',
    'cipher.algo_atbash': 'Atbash (Ters Alfabe)',
    'cipher.algo_base64': 'Base64 Encode / Decode',
    'cipher.algo_hash_sha256': 'SHA-256 Cryptographic Hash',
    'cipher.algo_hash_sha1': 'SHA-1 Cryptographic Hash',
    'cipher.shift_key': 'KAYDIRMA ANAHTARI (SHIFT)',
    'cipher.vigenere_key': 'ANAHTAR KELİME (KEYWORD)',
    'cipher.vigenere_key_placeholder': 'Örn: KEY / FINORA',
    'cipher.vigenere_key_error': 'Lütfen anahtar kelime girin.',
    'cipher.alphabet': 'ALFABE SEÇİMİ',
    'cipher.plain_text': 'AÇIK METİN (PLAIN TEXT)',
    'cipher.cipher_text': 'ŞİFRELİ METİN (CIPHER TEXT)',
    'cipher.placeholder_encrypt': 'Şifrelenecek metni yazın...',
    'cipher.placeholder_decrypt': 'Çözülecek şifreli metni yazın...',
    'cipher.info_text': 'Sezar, Vigenère, ROT13, Atbash şifrelemeleri ve SHA-256 / Base64 araçları şifreleme motorumuzda yer almaktadır.',
    'cipher.brute_force_title': 'SEZAR BRUTE-FORCE / OLASI TÜM ŞİFRE ÇÖZÜMLERİ',
    'cipher.brute_force_desc': 'Anahtarını bilmediğiniz Sezar şifreli metinlerin tüm muhtemel kaydırmalarını inceleyin:',
    
    'nav.audio_visualizer': 'Ses Görselleştirici & Kaydedici',
    'nav.decision_maker': 'Karar Çarkı',

    // Audio Visualizer Tool
    'audio.title': 'SES GÖRSELLEŞTİRİCİ &',
    'audio.title_accent': 'KAYDEDİCİ',
    'audio.desc': 'Mikrofonunuzdan veya yüklediğiniz ses dosyasından canlı ses spektrumu oluşturun, ses kaydedin ve indirin.',
    'audio.mode_mic': 'MİKROFON GİRDİSİ',
    'audio.mode_file': 'SES DOSYASI YÜKLE',
    'audio.start_mic': 'MİKROFONU BAŞLAT',
    'audio.stop_mic': 'MİKROFONU DURDUR',
    'audio.start_rec': 'KAYDI BAŞLAT',
    'audio.stop_rec': 'KAYDI DURDUR',
    'audio.recording': 'KAYDEDİLİYOR...',
    'audio.rec_ready': 'KAYIT HAZIR',
    'audio.download_rec': 'KAYDI İNDİR (.WEBM)',
    'audio.play_rec': 'KAYDI DİNLE',
    'audio.pause_rec': 'DURAKLAT',
    'audio.visual_style': 'GÖRSELLEŞTİRME STİLİ',
    'audio.style_bars': 'Frekans Çubukları',
    'audio.style_wave': 'Osiloskop Dalga',
    'audio.style_circle': 'Dairesel Spektrum',
    'audio.upload_prompt': 'Bir ses dosyası sürükleyin veya seçin (.mp3, .wav, .ogg)',
    'audio.info_text': 'Tüm ses işleme ve görselleştirme işlemleri Web Audio API kullanılarak tarayıcınızda gerçekleştirilir. Verileriniz hiçbir sunucuya iletilmez.',

    // Decision Maker Tool
    'decision.title': 'KARAR',
    'decision.title_accent': 'ÇARKI',
    'decision.desc': 'Seçeneklerinizi girin, çarkı çevirin ve kararsız kaldığınız konularda eğlenceli şekilde seçim yapın!',
    'decision.spin': 'ÇARKI ÇEVİR',
    'decision.spinning': 'DÖNÜYOR...',
    'decision.winner_title': 'KAZANAN SEÇENEK',
    'decision.options_list': 'SEÇENEK LİSTESİ',
    'decision.add_option': 'SEÇENEK EKLE',
    'decision.placeholder_option': 'Seçenek adı girin...',
    'decision.presets': 'HAZIR ŞABLONLAR',
    'decision.preset_food': 'Ne Yesek?',
    'decision.preset_yesno': 'Evet / Hayır',
    'decision.preset_numbers': '1 - 10 Sayı',
    'decision.preset_activity': 'Hafta Sonu Etkinliği',
    'decision.history': 'KAZANANLAR GEÇMİŞİ',
    'decision.clear_history': 'Geçmişi Temizle',
    'decision.sound_effects': 'Ses Efektleri',
    'decision.save_template': 'ŞABLON OLARAK KAYDET',
    'decision.template_name_prompt': 'Şablon İsmi Girin:',
    'decision.my_templates': 'ÖZEL ŞABLONLARIM',
    'decision.share_wheel': 'ŞABLONU PAYLAŞ (URL)',
    'decision.share_copied': 'BAĞLANTI KOPYALANDI!',
    'decision.info_text': 'Çark fiziği ve ses efektleri tarayıcınızın Canvas & Web Audio motorunda çalışır.',

    'nav.typing_test': 'Klavye Hız Testi',
    'nav.atmosphere_mixer': 'Arka Plan Ortam Sesleri',
    'nav.pixel_art': 'Pixel Art Çizim Stüdyosu',
    'nav.reaction_test': 'Refleks & Tepki Ölçer',

    // Typing Test
    'typing.title': 'KLAVYE HIZ',
    'typing.title_accent': 'TESTİ (WPM)',
    'typing.desc': 'Yazma hızınızı (WPM), doğruluğunuzu ve tuş vuruşlarınızı anlık olarak test edin ve geliştirin.',
    'typing.wpm': 'WPM (Kelime/Dk)',
    'typing.accuracy': 'DOĞRULUK',
    'typing.time': 'SÜRE',
    'typing.restart': 'YENİDEN BAŞLAT',
    'typing.start_prompt': 'Yazmaya başlamak için aşağıdaki kutuya tıklayın ve yazın...',
    'typing.result_title': 'TEST SONUCU',

    // Atmosphere Mixer
    'atmosphere.title': 'ARKA PLAN ORTAM',
    'atmosphere.title_accent': 'SESLERİ MİKSERİ',
    'atmosphere.desc': 'Odaklanma, çalışma ve rahatlama için yağmur, doğa, rüzgar ve kafe seslerini karıştırarak kendi atmosferinizi yaratın.',
    'atmosphere.rain': 'Yağmur Sesleri 🌧️',
    'atmosphere.thunder': 'Gök Gürültüsü 🌩️',
    'atmosphere.waves': 'Deniz Dalgaları 🌊',
    'atmosphere.wind': 'Rüzgar Esintisi 🌬️',
    'atmosphere.fire': 'Şömine Ateşi 🔥',
    'atmosphere.cafe': 'Kafe Ortamı ☕',
    'atmosphere.birds': 'Orman Kuşları 🐦',
    'atmosphere.stop_all': 'TÜM SESLERİ DURDUR',

    // Pixel Art Studio
    'pixel.title': 'PIXEL ART',
    'pixel.title_accent': 'ÇİZİM STÜDYOSU',
    'pixel.desc': '8x8, 16x16 veya 32x32 piksel ızgaralarında retro sanat eserleri çizin, katmanlayın ve PNG/SVG olarak indirin.',
    'pixel.size': 'IZGARA BOYUTU',
    'pixel.pencil': 'Kalem',
    'pixel.bucket': 'Kova',
    'pixel.eraser': 'Silgi',
    'pixel.clear': 'Tuvali Temizle',
    'pixel.export_png': 'PNG İNDİR',

    // Reaction Test
    'reaction.title': 'REFLEKS & TEPKİ',
    'reaction.title_accent': 'ÖLÇER',
    'reaction.desc': 'Sinyal kırmızıdan yeşile döndüğünde en hızlı şekilde tıklayın ve milisaniye cinsinden refleks sürenizi ölçün.',
    'reaction.wait': 'KIRMIZI: Yeşil Olmasını Bekleyin...',
    'reaction.click_now': 'ŞİMDİ TIKLAYIN!',
    'reaction.too_early': 'ÇOK ERKEN! Yeşil Olmadan Tıkladınız.',
    'reaction.ms': 'ms',
    'reaction.rank_god': '⚡ Işık Hızı (Süperinsan)',
    'reaction.rank_pro': '🐱 Siber Kedi (Çok Hızlı)',
    'reaction.rank_avg': '👨‍💻 Standart Oyuncu (İyi)',
    'reaction.rank_slow': '🐢 Kaplumbağa (Biraz Yavaş)',
  },
  en: {
    // Navbar
    'nav.title': "FINORA'S",
    'nav.title_accent': 'TOOL BAG',
    'nav.home': 'Home',
    'nav.tools': 'Tools',
    'nav.image_analysis': 'Image Analysis & Format',
    'nav.binary_converter': 'Binary Converter',
    'nav.password_generator': 'Password Generator',
    'nav.morse_converter': 'Morse Converter',
    'nav.color_explorer': 'Color Explorer',
    'nav.favicon_generator': 'Favicon Generator',
    'nav.json_converter': 'JSON to Model',
    'nav.ascii_art': 'ASCII Art Generator',
    'nav.qr_code': 'QR Code Generator',
    'nav.pomodoro': 'Pomodoro Timer',
    'nav.word_counter': 'Word Counter',
    
    // Home
    'home.badge': 'DIGITAL TOOLKIT V1.0',
    'home.title': "FINORA'S",
    'home.title_accent': 'TOOL BAG',
    'home.description': "Finora's tool bag offers modern, fast, and secure tools designed for developers and designers. All operations happen in your browser.",
    'home.cta_start': 'Get Started',
    'home.cta_github': 'View on GitHub',
    'home.features_title': 'Why Finora?',
    'home.feature_secure': 'Secure',
    'home.feature_secure_desc': 'Your data is never sent to our servers.',
    'home.feature_fast': 'Fast',
    'home.feature_fast_desc': 'Instant conversion and analysis results.',
    'home.feature_modern': 'Modern',
    'home.feature_modern_desc': 'User-friendly and stylish interface.',

    // Common
    'common.copy': 'COPY',
    'common.copied': 'COPIED',
    'common.clear': 'Clear',
    'common.input': 'Input',
    'common.output': 'Output',
    'common.result_placeholder': 'Result will appear here...',
    'common.random': 'Random',
    'common.info': 'INFO',
    'common.pro_tip': 'PRO TIP',

    // Binary Tool
    'binary.title': 'BINARY',
    'binary.title_accent': 'CONVERTER',
    'binary.desc': 'Instantly convert between text and Binary (base-2 system).',
    'binary.mode_text': 'TEXT',
    'binary.mode_binary': 'BINARY',
    'binary.placeholder_text': 'Type text to convert...',
    'binary.placeholder_binary': '01001000 01100101 01101100 01101100 01101111',

    // Password Tool
    'password.title': 'PASSWORD',
    'password.title_accent': 'GENERATOR',
    'password.desc': 'Generate secure and hard-to-crack passwords.',
    'password.length': 'PASSWORD LENGTH',
    'password.settings': 'CHARACTER SETTINGS',
    'password.uppercase': 'Uppercase (ABC)',
    'password.lowercase': 'Lowercase (abc)',
    'password.numbers': 'Numbers (123)',
    'password.symbols': 'Symbols (#$&)',
    'password.strength': 'STRENGTH LEVEL',
    'password.strength_very_weak': 'VERY WEAK',
    'password.strength_weak': 'WEAK',
    'password.strength_medium': 'MEDIUM',
    'password.strength_strong': 'STRONG',
    'password.strength_very_strong': 'VERY STRONG',
    'password.generate': 'GENERATE NEW PASSWORD',

    // Morse Tool
    'morse.title': 'MORSE',
    'morse.title_accent': 'CONVERTER',
    'morse.desc': 'Instantly convert between text and Morse code.',
    'morse.listen': 'LISTEN',
    'morse.info_text': 'Use \'/\' to separate words. A single space is used between characters.',

    // Color Tool
    'color.title': 'COLOR',
    'color.title_accent': 'EXPLORER',
    'color.desc': 'Capture perfect harmonies with the advanced color picker.',
    'color.hue': 'Hue',
    'color.selected': 'Selected Color',
    'color.rgb_values': 'RGB Values',
    'color.palette_title': 'Smart Color Palette',
    'color.pro_tip_text': 'The color picker uses the HSV model, which is closer to how human eyes perceive colors.',

    // Image Tool
    'image.title': 'IMAGE',
    'image.title_accent': 'ANALYSIS',
    'image.desc': 'Analyze your images, change formats, and see details.',
    'image.drop': 'Drop image here or click to select',
    'image.analyzing': 'Analyzing...',
    'image.details': 'Image Details',
    'image.format': 'Format',
    'image.dimensions': 'Dimensions',
    'image.size': 'File Size',
    'image.actions': 'Actions',
    'image.convert_to': 'Convert to',

    // Favicon Tool
    'favicon.title': 'FAVICON',
    'favicon.title_accent': 'GENERATOR',
    'favicon.desc': 'Convert your logo into a professional favicon package for all browsers and devices.',
    'favicon.download_pack': 'DOWNLOAD PACK (.ZIP)',
    'favicon.html_code': 'HTML CODE',
    'favicon.preview_all': 'Preview All Sizes',
    'favicon.info_text': 'Generated package includes 16x16, 32x32, 180x180 (Apple Touch), and 192x192, 512x512 (Android) sizes.',

    // JSON Converter Tool
    'json.title': 'JSON',
    'json.title_accent': 'TO MODEL',
    'json.desc': 'Instantly convert your JSON data into TypeScript, Go, or Java models.',
    'json.placeholder': 'Paste your JSON data here...',
    'json.select_lang': 'SELECT TARGET LANGUAGE',
    'json.root_name': 'ROOT CLASS NAME',
    'json.error_invalid': 'Invalid JSON format. Please check your input.',
    'json.empty_warning': 'No JSON data found to convert.',

    // ASCII Tool
    'ascii.title': 'ASCII',
    'ascii.title_accent': 'ART GENERATOR',
    'ascii.desc': 'Convert your text or images into cool ASCII characters.',
    'ascii.mode_text': 'TEXT',
    'ascii.mode_image': 'IMAGE',
    'ascii.placeholder': 'Type text to convert to ASCII art...',
    'ascii.settings': 'SETTINGS',
    'ascii.font': 'FONT',
    'ascii.width': 'WIDTH',
    'ascii.contrast': 'CONTRAST',
    'ascii.chars': 'CHARACTER SET',
    'tools.title': 'TOOLS',
    'tools.title_accent': 'CATALOG',
    'tools.launch': 'LAUNCH TOOL',

    // QR Code Tool
    'qr.title': 'QR CODE',
    'qr.title_accent': 'GENERATOR',
    'qr.desc': 'Instantly generate QR codes for URLs, text, email, or phone numbers.',
    'qr.input_type': 'INPUT TYPE',
    'qr.input_label': 'CONTENT',
    'qr.type_url': 'URL',
    'qr.type_text': 'TEXT',
    'qr.type_email': 'EMAIL',
    'qr.type_phone': 'PHONE',
    'qr.placeholder_text': 'Type text to convert to QR code...',
    'qr.generate': 'GENERATE QR CODE',
    'qr.generating': 'GENERATING...',
    'qr.generated': 'QR CODE READY',
    'qr.download': 'DOWNLOAD PNG',
    'qr.preview_placeholder': 'Your QR code will appear here...',
    'qr.error_empty': 'Please enter a value.',
    'qr.error_generate': 'An error occurred while generating QR code.',
    'qr.info_text': 'QR codes are generated with high error correction level (H). All processing happens in your browser, your data is never sent to any server.',

    // Pomodoro Tool
    'pomodoro.title': 'POMODORO',
    'pomodoro.title_accent': 'TIMER',
    'pomodoro.desc': 'Stay focused and boost your productivity with the Pomodoro technique.',
    'pomodoro.session_length': 'SESSION LENGTH',
    'pomodoro.presets': 'QUICK PRESETS',
    'pomodoro.start': 'START',
    'pomodoro.pause': 'PAUSE',
    'pomodoro.resume': 'RESUME',
    'pomodoro.reset': 'RESET',
    'pomodoro.times_up': "TIME'S UP!",
    'pomodoro.status_running': 'FOCUS MODE',
    'pomodoro.status_paused': 'PAUSED',
    'pomodoro.status_ready': 'READY TO START',
    'pomodoro.technique': 'POMODORO TECHNIQUE',
    'pomodoro.tip_focus': '25 min Focus',
    'pomodoro.tip_focus_desc': 'Focus on a single task without interruptions. Turn off notifications.',
    'pomodoro.tip_break': '5 min Break',
    'pomodoro.tip_break_desc': 'Take a short break after each session. Take a long break every 4 sessions.',
    'pomodoro.info_text': 'The Pomodoro Technique is a time management method developed by Francesco Cirillo. All processing happens in your browser.',

    // Word Counter Tool
    'wordcounter.title': 'WORD',
    'wordcounter.title_accent': 'COUNTER',
    'wordcounter.desc': 'Paste your text and instantly see word, character, sentence, and paragraph counts.',
    'wordcounter.input_label': 'YOUR TEXT',
    'wordcounter.placeholder': 'Type or paste your text here...',
    'wordcounter.paste': 'PASTE',
    'wordcounter.words': 'WORDS',
    'wordcounter.characters': 'CHARACTERS',
    'wordcounter.chars_no_space': 'NO SPACES',
    'wordcounter.sentences': 'SENTENCES',
    'wordcounter.paragraphs': 'PARAGRAPHS',
    'wordcounter.read_time': 'read time',
    'wordcounter.info_text': 'Statistics update in real time as you type. All processing happens in your browser.',

    'nav.unix_timestamp': 'Unix Timestamp',
    'nav.url_shortener': 'URL Shortener',
    
    // Unix Tool
    'unix.title': 'UNIX',
    'unix.title_accent': 'TIMESTAMP',
    'unix.desc': 'Instantly and easily convert between epoch timestamps and human-readable dates.',
    'unix.current_epoch': 'CURRENT UNIX TIMESTAMP',
    'unix.local_time': 'Local Date & Time',
    'unix.utc_time': 'UTC Date & Time',
    'unix.relative_time': 'Relative Time',
    'unix.convert_from_epoch': 'Convert Unix Timestamp',
    'unix.convert_to_epoch': 'Convert Date to Unix Timestamp',
    'unix.placeholder_epoch': 'Enter seconds or milliseconds...',
    'unix.btn_now': 'Get Current Time',
    'unix.seconds': 'Seconds',
    'unix.milliseconds': 'Milliseconds',
    'unix.date_select': 'Select a Date',

    // URL Shortener
    'url.title': 'URL',
    'url.title_accent': 'SHORTENER',
    'url.desc': 'Shorten your long web links, generate their QR codes, and analyze URL components.',
    'url.placeholder': 'Enter long URL to shorten (https://... or http://...)',
    'url.shorten': 'SHORTEN',
    'url.shortening': 'SHORTENING...',
    'url.result_label': 'SHORTENED URL',
    'url.qr_title': 'LINK QR CODE',
    'url.analysis_title': 'URL COMPONENT ANALYSIS',
    'url.param_name': 'PARAMETER',
    'url.param_value': 'VALUE',
    'url.error_invalid': 'Please enter a valid URL (must start with http:// or https://).',
    'url.error_failed': 'An error occurred while shortening the URL. Please try again.',

    'nav.linkbag': 'Finora LinkBag',
    
    // LinkBag Tool
    'linkbag.title': 'FINORA',
    'linkbag.title_accent': 'LINKBAG',
    'linkbag.desc': 'Design, share, or download a premium profile page that gathers all your links in one place.',
    'linkbag.editor': 'PROFILE EDITOR',
    'linkbag.preview': 'LIVE PREVIEW',
    'linkbag.profile_name': 'Your Name / Title',
    'linkbag.profile_bio': 'Short Bio',
    'linkbag.profile_avatar': 'Profile Picture (URL)',
    'linkbag.profile_avatar_upload': 'Choose Image (Base64)',
    'linkbag.add_link': 'ADD LINK',
    'linkbag.link_title': 'Link Title',
    'linkbag.link_url': 'URL Address',
    'linkbag.link_icon': 'Icon',
    'linkbag.select_theme': 'SELECT THEME',
    'linkbag.theme_glass': 'Glassmorphism',
    'linkbag.theme_cyberpunk': 'Cyberpunk',
    'linkbag.theme_minimalist': 'Minimalist',
    'linkbag.theme_brutalism': 'Neo-Brutalism',
    'linkbag.theme_synthwave': 'Synthwave',
    'linkbag.theme_matrix': 'Matrix',
    'linkbag.theme_sakura': 'Cozy Sakura',
    'linkbag.theme_holographic': 'Aurora Hologram',
    'linkbag.theme_claymorphism': 'Claymorphism',
    'linkbag.share_profile': 'COPY SHAREABLE LINK',
    'linkbag.download_html': 'DOWNLOAD HTML FILE',

    'nav.cipher': 'Encrypt & Decrypt',
    'nav.file_share': 'File Sharing',
    
    // File Share Tool
    'fileshare.title': 'FILE',
    'fileshare.title_accent': 'SHARING & STORAGE',
    'fileshare.desc': 'Upload your files securely, encrypt with a password, set expiration time, and share via link or QR code instantly.',
    'fileshare.drop_title': 'Drag & drop your file here or click to browse',
    'fileshare.drop_sub': 'Any file format supported (Images, Videos, Docs, ZIP etc.)',
    'fileshare.select_file': 'SELECT FILE',
    'fileshare.file_details': 'FILE DETAILS',
    'fileshare.filename': 'Filename',
    'fileshare.filesize': 'File Size',
    'fileshare.filetype': 'Type',
    'fileshare.uploaded_at': 'Upload Date',
    'fileshare.security_settings': 'SECURITY & EXPIRATION SETTINGS',
    'fileshare.enable_password': 'Add Password Protection (AES-256 Encryption)',
    'fileshare.password_placeholder': 'Enter file access password...',
    'fileshare.retention': 'Expiration Time',
    'fileshare.retention_1h': '1 Hour',
    'fileshare.retention_24h': '24 Hours',
    'fileshare.retention_7d': '7 Days',
    'fileshare.retention_30d': '30 Days',
    'fileshare.retention_never': 'No Expiration (Local Storage)',
    'fileshare.upload_btn': 'UPLOAD FILE & GENERATE LINK',
    'fileshare.uploading': 'ENCRYPTING & UPLOADING...',
    'fileshare.share_link': 'SHAREABLE LINK',
    'fileshare.download_link': 'DIRECT DOWNLOAD LINK',
    'fileshare.qr_title': 'MOBILE QR DOWNLOAD CODE',
    'fileshare.preview_title': 'FILE PREVIEW',
    'fileshare.download_btn': 'DOWNLOAD FILE',
    'fileshare.decrypt_title': 'PROTECTED FILE ACCESS',
    'fileshare.enter_password': 'Enter password to unlock & download file:',
    'fileshare.decrypt_btn': 'DECRYPT & ACCESS',
    'fileshare.wrong_password': 'Incorrect password! Please try again.',
    'fileshare.history_title': 'MY UPLOADED FILES / HISTORY',
    'fileshare.no_history': 'No uploaded files yet.',
    'fileshare.downloads': 'Downloads',
    'fileshare.expires': 'Expires',
    'fileshare.delete': 'Delete',
    'fileshare.info_text': 'This file sharing tool encrypts your files client-side using Web Crypto API (AES-256) and creates secure shareable links.',
    
    // Cipher Tool
    'cipher.title': 'ENCRYPT &',
    'cipher.title_accent': 'DECRYPT',
    'cipher.desc': 'Safely encrypt or decrypt your text using Caesar cipher and modern methods.',
    'cipher.mode_encrypt': 'ENCRYPT',
    'cipher.mode_decrypt': 'DECRYPT',
    'cipher.settings': 'ENCRYPTION SETTINGS',
    'cipher.algorithm': 'ENCRYPTION ALGORITHM',
    'cipher.algo_caesar': 'Caesar Cipher',
    'cipher.algo_vigenere': 'Vigenère Cipher',
    'cipher.algo_rot13': 'ROT13 Cipher',
    'cipher.algo_atbash': 'Atbash (Reverse Alphabet)',
    'cipher.algo_base64': 'Base64 Encode / Decode',
    'cipher.algo_hash_sha256': 'SHA-256 Cryptographic Hash',
    'cipher.algo_hash_sha1': 'SHA-1 Cryptographic Hash',
    'cipher.shift_key': 'SHIFT KEY',
    'cipher.vigenere_key': 'SECRET KEYWORD',
    'cipher.vigenere_key_placeholder': 'e.g. KEY / FINORA',
    'cipher.vigenere_key_error': 'Please enter a secret key.',
    'cipher.alphabet': 'ALPHABET',
    'cipher.plain_text': 'PLAIN TEXT',
    'cipher.cipher_text': 'CIPHER TEXT',
    'cipher.placeholder_encrypt': 'Type text to encrypt...',
    'cipher.placeholder_decrypt': 'Type cipher text to decrypt...',
    'cipher.info_text': 'Caesar, Vigenère, ROT13, Atbash ciphers along with SHA-256 and Base64 tools are available in our encryption engine.',
    'cipher.brute_force_title': 'CAESAR BRUTE-FORCE / ALL POSSIBLE SHIFTS',
    'cipher.brute_force_desc': 'Analyze all possible shift key candidates for unknown Caesar ciphertexts:',

    'nav.audio_visualizer': 'Audio Visualizer & Recorder',
    'nav.decision_maker': 'Decision Maker',

    // Audio Visualizer Tool
    'audio.title': 'AUDIO VISUALIZER &',
    'audio.title_accent': 'RECORDER',
    'audio.desc': 'Generate a live audio spectrum from your microphone or audio file, record audio, and download recordings.',
    'audio.mode_mic': 'MICROPHONE INPUT',
    'audio.mode_file': 'UPLOAD AUDIO FILE',
    'audio.start_mic': 'START MICROPHONE',
    'audio.stop_mic': 'STOP MICROPHONE',
    'audio.start_rec': 'START RECORDING',
    'audio.stop_rec': 'STOP RECORDING',
    'audio.recording': 'RECORDING...',
    'audio.rec_ready': 'RECORDING READY',
    'audio.download_rec': 'DOWNLOAD RECORDING (.WEBM)',
    'audio.play_rec': 'PLAY RECORDING',
    'audio.pause_rec': 'PAUSE',
    'audio.visual_style': 'VISUALIZATION STYLE',
    'audio.style_bars': 'Frequency Bars',
    'audio.style_wave': 'Oscilloscope Wave',
    'audio.style_circle': 'Circular Spectrum',
    'audio.upload_prompt': 'Drag & drop an audio file or click to choose (.mp3, .wav, .ogg)',
    'audio.info_text': 'All audio processing and visualization is performed client-side using the Web Audio API. Your data is never sent to any server.',

    // Decision Maker Tool
    'decision.title': 'DECISION',
    'decision.title_accent': 'MAKER WHEEL',
    'decision.desc': 'Enter your options, spin the wheel, and let fate decide in a fun interactive way!',
    'decision.spin': 'SPIN THE WHEEL',
    'decision.spinning': 'SPINNING...',
    'decision.winner_title': 'WINNING OPTION',
    'decision.options_list': 'OPTIONS LIST',
    'decision.add_option': 'ADD OPTION',
    'decision.placeholder_option': 'Enter option title...',
    'decision.presets': 'PRESETS',
    'decision.preset_food': 'What to Eat?',
    'decision.preset_yesno': 'Yes / No',
    'decision.preset_numbers': '1 - 10 Numbers',
    'decision.preset_activity': 'Weekend Activity',
    'decision.history': 'WINNERS HISTORY',
    'decision.clear_history': 'Clear History',
    'decision.sound_effects': 'Sound Effects',
    'decision.save_template': 'SAVE AS TEMPLATE',
    'decision.template_name_prompt': 'Enter Template Name:',
    'decision.my_templates': 'MY CUSTOM TEMPLATES',
    'decision.share_wheel': 'SHARE TEMPLATE (URL)',
    'decision.share_copied': 'LINK COPIED!',
    'decision.info_text': 'Wheel physics and audio effects run entirely on your browser HTML5 Canvas & Web Audio engine.',

    'nav.typing_test': 'Typing Speed Test',
    'nav.atmosphere_mixer': 'Atmosphere Sound Mixer',
    'nav.pixel_art': 'Pixel Art Studio',
    'nav.reaction_test': 'Reaction Time Test',

    // Typing Test
    'typing.title': 'TYPING SPEED',
    'typing.title_accent': 'TEST (WPM)',
    'typing.desc': 'Test and improve your typing speed (WPM), accuracy, and keystrokes in real time.',
    'typing.wpm': 'WPM (Words/Min)',
    'typing.accuracy': 'ACCURACY',
    'typing.time': 'TIME',
    'typing.restart': 'RESTART TEST',
    'typing.start_prompt': 'Click the box below and start typing to begin test...',
    'typing.result_title': 'TEST RESULT',

    // Atmosphere Mixer
    'atmosphere.title': 'ATMOSPHERE AMBIENT',
    'atmosphere.title_accent': 'SOUND MIXER',
    'atmosphere.desc': 'Mix rain, nature, wind, and cafe ambient sounds for focus, work, and relaxation.',
    'atmosphere.rain': 'Rain Sounds 🌧️',
    'atmosphere.thunder': 'Thunderstorm 🌩️',
    'atmosphere.waves': 'Ocean Waves 🌊',
    'atmosphere.wind': 'Wind Breeze 🌬️',
    'atmosphere.fire': 'Fireplace 🔥',
    'atmosphere.cafe': 'Cafe Ambience ☕',
    'atmosphere.birds': 'Forest Birds 🐦',
    'atmosphere.stop_all': 'STOP ALL SOUNDS',

    // Pixel Art Studio
    'pixel.title': 'PIXEL ART',
    'pixel.title_accent': 'STUDIO',
    'pixel.desc': 'Draw retro pixel artworks on 8x8, 16x16, or 32x32 grids and download as PNG/SVG.',
    'pixel.size': 'GRID SIZE',
    'pixel.pencil': 'Pencil',
    'pixel.bucket': 'Bucket Fill',
    'pixel.eraser': 'Eraser',
    'pixel.clear': 'Clear Canvas',
    'pixel.export_png': 'DOWNLOAD PNG',

    // Reaction Test
    'reaction.title': 'REACTION TIME',
    'reaction.title_accent': 'TESTER',
    'reaction.desc': 'Click as fast as you can when the signal turns green to measure your reaction time in milliseconds.',
    'reaction.wait': 'RED: Wait for Green Signal...',
    'reaction.click_now': 'CLICK NOW!',
    'reaction.too_early': 'TOO EARLY! Clicked before green.',
    'reaction.ms': 'ms',
    'reaction.rank_god': '⚡ Light Speed (Superhuman)',
    'reaction.rank_pro': '🐱 Cyber Cat (Ultra Fast)',
    'reaction.rank_avg': '👨‍💻 Gamer Average (Good)',
    'reaction.rank_slow': '🐢 Turtle Speed (A Bit Slow)',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('finora_lang');
    return (saved as Language) || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('finora_lang', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
